// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: aggregates.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates {

  /// <summary>Holder for reflection information generated from aggregates.proto</summary>
  public static partial class AggregatesReflection {

    #region Descriptor
    /// <summary>File descriptor for aggregates.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AggregatesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBhZ2dyZWdhdGVzLnByb3RvEiZ2YmFydC5ldmVudHNfZGVtby5pbnZlbnRv",
            "cnkuYWdncmVnYXRlcxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90bxoeZ29v",
            "Z2xlL3Byb3RvYnVmL3dyYXBwZXJzLnByb3RvGh9nb29nbGUvcHJvdG9idWYv",
            "dGltZXN0YW1wLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZmllbGRfbWFzay5w",
            "cm90bxoTdmFsdWVfb2JqZWN0cy5wcm90byK6AQoGQ2hhbmdlEhMKC2VudGl0",
            "eV91dWlkGAEgASgJEi4KCmNoYW5nZWRfYXQYAiABKAsyGi5nb29nbGUucHJv",
            "dG9idWYuVGltZXN0YW1wEhcKD3JldmlzaW9uX251bWJlchgFIAEoDRIjCgVl",
            "dmVudBgGIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkSLQoPcmVzdWx0aW5n",
            "X3N0YXRlGAcgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueSKOAQoHVmVoaWNs",
            "ZRIUCgx2ZWhpY2xlX3V1aWQYASABKAkSGwoTeWVhcl9vZl9tYW51ZmFjdHVy",
            "ZRgCIAEoBRINCgVtb2RlbBgDIAEoCRJBCgZlbmdpbmUYBCABKAsyMS52YmFy",
            "dC5ldmVudHNfZGVtby5pbnZlbnRvcnkudmFsdWVfb2JqZWN0cy5FbmdpbmUi",
            "pgEKCE1ldGFEYXRhEk8KB2VudHJpZXMYASADKAsyPi52YmFydC5ldmVudHNf",
            "ZGVtby5pbnZlbnRvcnkuYWdncmVnYXRlcy5NZXRhRGF0YS5NZXRhZGF0YUVu",
            "dHJ5GkkKDU1ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEisKBXZhbHVlGAIg",
            "ASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlIlIKDlZlaGljbGVD",
            "cmVhdGVkEkAKB3ZlaGljbGUYASABKAsyLy52YmFydC5ldmVudHNfZGVtby5p",
            "bnZlbnRvcnkuYWdncmVnYXRlcy5WZWhpY2xlIkcKDlZlaGljbGVEZWxldGVk",
            "EhQKDHZlaGljbGVfdXVpZBgBIAEoCRIfChd2ZWhpY2xlX3JldmlzaW9uX251",
            "bWJlchgCIAEoDSKCAQoOVmVoaWNsZVVwZGF0ZWQSQAoHdmVoaWNsZRgBIAEo",
            "CzIvLnZiYXJ0LmV2ZW50c19kZW1vLmludmVudG9yeS5hZ2dyZWdhdGVzLlZl",
            "aGljbGUSLgoKZmllbGRfbWFzaxgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5G",
            "aWVsZE1hc2tCOqoCN1ZCYXJ0LkV2ZW50c0RlbW8uSW52ZW50b3J5LkFnZ3Jl",
            "Z2F0b3IuRG9tYWluLkFnZ3JlZ2F0ZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, global::VBart.EventsDemo.Grpc.ValueObjects.ValueObjectsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Change), global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Change.Parser, new[]{ "EntityUuid", "ChangedAt", "RevisionNumber", "Event", "ResultingState" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle), global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle.Parser, new[]{ "VehicleUuid", "YearOfManufacture", "Model", "Engine" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData), global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Parser, new[]{ "Entries" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Types.MetadataEntry), global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Types.MetadataEntry.Parser, new[]{ "Key", "Value" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.VehicleCreated), global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.VehicleCreated.Parser, new[]{ "Vehicle" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.VehicleDeleted), global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.VehicleDeleted.Parser, new[]{ "VehicleUuid", "VehicleRevisionNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.VehicleUpdated), global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.VehicleUpdated.Parser, new[]{ "Vehicle", "FieldMask" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Change : pb::IMessage<Change>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Change> _parser = new pb::MessageParser<Change>(() => new Change());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Change> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.AggregatesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Change() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Change(Change other) : this() {
      entityUuid_ = other.entityUuid_;
      changedAt_ = other.changedAt_ != null ? other.changedAt_.Clone() : null;
      revisionNumber_ = other.revisionNumber_;
      event_ = other.event_ != null ? other.event_.Clone() : null;
      resultingState_ = other.resultingState_ != null ? other.resultingState_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Change Clone() {
      return new Change(this);
    }

    /// <summary>Field number for the "entity_uuid" field.</summary>
    public const int EntityUuidFieldNumber = 1;
    private string entityUuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EntityUuid {
      get { return entityUuid_; }
      set {
        entityUuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "changed_at" field.</summary>
    public const int ChangedAtFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp changedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ChangedAt {
      get { return changedAt_; }
      set {
        changedAt_ = value;
      }
    }

    /// <summary>Field number for the "revision_number" field.</summary>
    public const int RevisionNumberFieldNumber = 5;
    private uint revisionNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint RevisionNumber {
      get { return revisionNumber_; }
      set {
        revisionNumber_ = value;
      }
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Any event_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any Event {
      get { return event_; }
      set {
        event_ = value;
      }
    }

    /// <summary>Field number for the "resulting_state" field.</summary>
    public const int ResultingStateFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Any resultingState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any ResultingState {
      get { return resultingState_; }
      set {
        resultingState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Change);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Change other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityUuid != other.EntityUuid) return false;
      if (!object.Equals(ChangedAt, other.ChangedAt)) return false;
      if (RevisionNumber != other.RevisionNumber) return false;
      if (!object.Equals(Event, other.Event)) return false;
      if (!object.Equals(ResultingState, other.ResultingState)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityUuid.Length != 0) hash ^= EntityUuid.GetHashCode();
      if (changedAt_ != null) hash ^= ChangedAt.GetHashCode();
      if (RevisionNumber != 0) hash ^= RevisionNumber.GetHashCode();
      if (event_ != null) hash ^= Event.GetHashCode();
      if (resultingState_ != null) hash ^= ResultingState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityUuid);
      }
      if (changedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedAt);
      }
      if (RevisionNumber != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(RevisionNumber);
      }
      if (event_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Event);
      }
      if (resultingState_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ResultingState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntityUuid);
      }
      if (changedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedAt);
      }
      if (RevisionNumber != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(RevisionNumber);
      }
      if (event_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Event);
      }
      if (resultingState_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ResultingState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EntityUuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityUuid);
      }
      if (changedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedAt);
      }
      if (RevisionNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RevisionNumber);
      }
      if (event_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Event);
      }
      if (resultingState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResultingState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Change other) {
      if (other == null) {
        return;
      }
      if (other.EntityUuid.Length != 0) {
        EntityUuid = other.EntityUuid;
      }
      if (other.changedAt_ != null) {
        if (changedAt_ == null) {
          ChangedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ChangedAt.MergeFrom(other.ChangedAt);
      }
      if (other.RevisionNumber != 0) {
        RevisionNumber = other.RevisionNumber;
      }
      if (other.event_ != null) {
        if (event_ == null) {
          Event = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Event.MergeFrom(other.Event);
      }
      if (other.resultingState_ != null) {
        if (resultingState_ == null) {
          ResultingState = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        ResultingState.MergeFrom(other.ResultingState);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EntityUuid = input.ReadString();
            break;
          }
          case 18: {
            if (changedAt_ == null) {
              ChangedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ChangedAt);
            break;
          }
          case 40: {
            RevisionNumber = input.ReadUInt32();
            break;
          }
          case 50: {
            if (event_ == null) {
              Event = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Event);
            break;
          }
          case 58: {
            if (resultingState_ == null) {
              ResultingState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ResultingState);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EntityUuid = input.ReadString();
            break;
          }
          case 18: {
            if (changedAt_ == null) {
              ChangedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ChangedAt);
            break;
          }
          case 40: {
            RevisionNumber = input.ReadUInt32();
            break;
          }
          case 50: {
            if (event_ == null) {
              Event = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Event);
            break;
          }
          case 58: {
            if (resultingState_ == null) {
              ResultingState = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ResultingState);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Vehicle : pb::IMessage<Vehicle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Vehicle> _parser = new pb::MessageParser<Vehicle>(() => new Vehicle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Vehicle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.AggregatesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vehicle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vehicle(Vehicle other) : this() {
      vehicleUuid_ = other.vehicleUuid_;
      yearOfManufacture_ = other.yearOfManufacture_;
      model_ = other.model_;
      engine_ = other.engine_ != null ? other.engine_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vehicle Clone() {
      return new Vehicle(this);
    }

    /// <summary>Field number for the "vehicle_uuid" field.</summary>
    public const int VehicleUuidFieldNumber = 1;
    private string vehicleUuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string VehicleUuid {
      get { return vehicleUuid_; }
      set {
        vehicleUuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "year_of_manufacture" field.</summary>
    public const int YearOfManufactureFieldNumber = 2;
    private int yearOfManufacture_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int YearOfManufacture {
      get { return yearOfManufacture_; }
      set {
        yearOfManufacture_ = value;
      }
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 3;
    private string model_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "engine" field.</summary>
    public const int EngineFieldNumber = 4;
    private global::VBart.EventsDemo.Grpc.ValueObjects.Engine engine_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VBart.EventsDemo.Grpc.ValueObjects.Engine Engine {
      get { return engine_; }
      set {
        engine_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Vehicle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Vehicle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VehicleUuid != other.VehicleUuid) return false;
      if (YearOfManufacture != other.YearOfManufacture) return false;
      if (Model != other.Model) return false;
      if (!object.Equals(Engine, other.Engine)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (VehicleUuid.Length != 0) hash ^= VehicleUuid.GetHashCode();
      if (YearOfManufacture != 0) hash ^= YearOfManufacture.GetHashCode();
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      if (engine_ != null) hash ^= Engine.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VehicleUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VehicleUuid);
      }
      if (YearOfManufacture != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(YearOfManufacture);
      }
      if (Model.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Model);
      }
      if (engine_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Engine);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VehicleUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VehicleUuid);
      }
      if (YearOfManufacture != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(YearOfManufacture);
      }
      if (Model.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Model);
      }
      if (engine_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Engine);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (VehicleUuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VehicleUuid);
      }
      if (YearOfManufacture != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(YearOfManufacture);
      }
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      if (engine_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Engine);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Vehicle other) {
      if (other == null) {
        return;
      }
      if (other.VehicleUuid.Length != 0) {
        VehicleUuid = other.VehicleUuid;
      }
      if (other.YearOfManufacture != 0) {
        YearOfManufacture = other.YearOfManufacture;
      }
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      if (other.engine_ != null) {
        if (engine_ == null) {
          Engine = new global::VBart.EventsDemo.Grpc.ValueObjects.Engine();
        }
        Engine.MergeFrom(other.Engine);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VehicleUuid = input.ReadString();
            break;
          }
          case 16: {
            YearOfManufacture = input.ReadInt32();
            break;
          }
          case 26: {
            Model = input.ReadString();
            break;
          }
          case 34: {
            if (engine_ == null) {
              Engine = new global::VBart.EventsDemo.Grpc.ValueObjects.Engine();
            }
            input.ReadMessage(Engine);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            VehicleUuid = input.ReadString();
            break;
          }
          case 16: {
            YearOfManufacture = input.ReadInt32();
            break;
          }
          case 26: {
            Model = input.ReadString();
            break;
          }
          case 34: {
            if (engine_ == null) {
              Engine = new global::VBart.EventsDemo.Grpc.ValueObjects.Engine();
            }
            input.ReadMessage(Engine);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MetaData : pb::IMessage<MetaData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MetaData> _parser = new pb::MessageParser<MetaData>(() => new MetaData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MetaData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.AggregatesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetaData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetaData(MetaData other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetaData Clone() {
      return new MetaData(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Types.MetadataEntry> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Types.MetadataEntry.Parser);
    private readonly pbc::RepeatedField<global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Types.MetadataEntry> entries_ = new pbc::RepeatedField<global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Types.MetadataEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Types.MetadataEntry> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MetaData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MetaData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MetaData other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MetaData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class MetadataEntry : pb::IMessage<MetadataEntry>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<MetadataEntry> _parser = new pb::MessageParser<MetadataEntry>(() => new MetadataEntry());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<MetadataEntry> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.MetaData.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadataEntry() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadataEntry(MetadataEntry other) : this() {
          key_ = other.key_;
          Value = other.Value;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MetadataEntry Clone() {
          return new MetadataEntry(this);
        }

        /// <summary>Field number for the "key" field.</summary>
        public const int KeyFieldNumber = 1;
        private string key_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Key {
          get { return key_; }
          set {
            key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "value" field.</summary>
        public const int ValueFieldNumber = 2;
        private static readonly pb::FieldCodec<string> _single_value_codec = pb::FieldCodec.ForClassWrapper<string>(18);
        private string value_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Value {
          get { return value_; }
          set {
            value_ = value;
          }
        }


        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as MetadataEntry);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(MetadataEntry other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Key != other.Key) return false;
          if (Value != other.Value) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Key.Length != 0) hash ^= Key.GetHashCode();
          if (value_ != null) hash ^= Value.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Key.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Key);
          }
          if (value_ != null) {
            _single_value_codec.WriteTagAndValue(output, Value);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Key.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Key);
          }
          if (value_ != null) {
            _single_value_codec.WriteTagAndValue(ref output, Value);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Key.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
          }
          if (value_ != null) {
            size += _single_value_codec.CalculateSizeWithTag(Value);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(MetadataEntry other) {
          if (other == null) {
            return;
          }
          if (other.Key.Length != 0) {
            Key = other.Key;
          }
          if (other.value_ != null) {
            if (value_ == null || other.Value != "") {
              Value = other.Value;
            }
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Key = input.ReadString();
                break;
              }
              case 18: {
                string value = _single_value_codec.Read(input);
                if (value_ == null || value != "") {
                  Value = value;
                }
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Key = input.ReadString();
                break;
              }
              case 18: {
                string value = _single_value_codec.Read(ref input);
                if (value_ == null || value != "") {
                  Value = value;
                }
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  public sealed partial class VehicleCreated : pb::IMessage<VehicleCreated>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VehicleCreated> _parser = new pb::MessageParser<VehicleCreated>(() => new VehicleCreated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VehicleCreated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.AggregatesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleCreated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleCreated(VehicleCreated other) : this() {
      vehicle_ = other.vehicle_ != null ? other.vehicle_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleCreated Clone() {
      return new VehicleCreated(this);
    }

    /// <summary>Field number for the "vehicle" field.</summary>
    public const int VehicleFieldNumber = 1;
    private global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle vehicle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle Vehicle {
      get { return vehicle_; }
      set {
        vehicle_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VehicleCreated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VehicleCreated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Vehicle, other.Vehicle)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (vehicle_ != null) hash ^= Vehicle.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (vehicle_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Vehicle);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (vehicle_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Vehicle);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (vehicle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vehicle);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VehicleCreated other) {
      if (other == null) {
        return;
      }
      if (other.vehicle_ != null) {
        if (vehicle_ == null) {
          Vehicle = new global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle();
        }
        Vehicle.MergeFrom(other.Vehicle);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (vehicle_ == null) {
              Vehicle = new global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle();
            }
            input.ReadMessage(Vehicle);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (vehicle_ == null) {
              Vehicle = new global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle();
            }
            input.ReadMessage(Vehicle);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class VehicleDeleted : pb::IMessage<VehicleDeleted>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VehicleDeleted> _parser = new pb::MessageParser<VehicleDeleted>(() => new VehicleDeleted());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VehicleDeleted> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.AggregatesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleDeleted() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleDeleted(VehicleDeleted other) : this() {
      vehicleUuid_ = other.vehicleUuid_;
      vehicleRevisionNumber_ = other.vehicleRevisionNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleDeleted Clone() {
      return new VehicleDeleted(this);
    }

    /// <summary>Field number for the "vehicle_uuid" field.</summary>
    public const int VehicleUuidFieldNumber = 1;
    private string vehicleUuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string VehicleUuid {
      get { return vehicleUuid_; }
      set {
        vehicleUuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "vehicle_revision_number" field.</summary>
    public const int VehicleRevisionNumberFieldNumber = 2;
    private uint vehicleRevisionNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint VehicleRevisionNumber {
      get { return vehicleRevisionNumber_; }
      set {
        vehicleRevisionNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VehicleDeleted);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VehicleDeleted other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VehicleUuid != other.VehicleUuid) return false;
      if (VehicleRevisionNumber != other.VehicleRevisionNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (VehicleUuid.Length != 0) hash ^= VehicleUuid.GetHashCode();
      if (VehicleRevisionNumber != 0) hash ^= VehicleRevisionNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VehicleUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VehicleUuid);
      }
      if (VehicleRevisionNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(VehicleRevisionNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VehicleUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VehicleUuid);
      }
      if (VehicleRevisionNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(VehicleRevisionNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (VehicleUuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VehicleUuid);
      }
      if (VehicleRevisionNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VehicleRevisionNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VehicleDeleted other) {
      if (other == null) {
        return;
      }
      if (other.VehicleUuid.Length != 0) {
        VehicleUuid = other.VehicleUuid;
      }
      if (other.VehicleRevisionNumber != 0) {
        VehicleRevisionNumber = other.VehicleRevisionNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VehicleUuid = input.ReadString();
            break;
          }
          case 16: {
            VehicleRevisionNumber = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            VehicleUuid = input.ReadString();
            break;
          }
          case 16: {
            VehicleRevisionNumber = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class VehicleUpdated : pb::IMessage<VehicleUpdated>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VehicleUpdated> _parser = new pb::MessageParser<VehicleUpdated>(() => new VehicleUpdated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VehicleUpdated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.AggregatesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleUpdated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleUpdated(VehicleUpdated other) : this() {
      vehicle_ = other.vehicle_ != null ? other.vehicle_.Clone() : null;
      fieldMask_ = other.fieldMask_ != null ? other.fieldMask_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VehicleUpdated Clone() {
      return new VehicleUpdated(this);
    }

    /// <summary>Field number for the "vehicle" field.</summary>
    public const int VehicleFieldNumber = 1;
    private global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle vehicle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle Vehicle {
      get { return vehicle_; }
      set {
        vehicle_ = value;
      }
    }

    /// <summary>Field number for the "field_mask" field.</summary>
    public const int FieldMaskFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.FieldMask fieldMask_;
    /// <summary>
    /// This is a FieldMask to indicate which fields are being updated.
    /// If this is left blank, that indicates all of the fields are being updated.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.FieldMask FieldMask {
      get { return fieldMask_; }
      set {
        fieldMask_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VehicleUpdated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VehicleUpdated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Vehicle, other.Vehicle)) return false;
      if (!object.Equals(FieldMask, other.FieldMask)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (vehicle_ != null) hash ^= Vehicle.GetHashCode();
      if (fieldMask_ != null) hash ^= FieldMask.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (vehicle_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Vehicle);
      }
      if (fieldMask_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FieldMask);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (vehicle_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Vehicle);
      }
      if (fieldMask_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FieldMask);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (vehicle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vehicle);
      }
      if (fieldMask_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FieldMask);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VehicleUpdated other) {
      if (other == null) {
        return;
      }
      if (other.vehicle_ != null) {
        if (vehicle_ == null) {
          Vehicle = new global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle();
        }
        Vehicle.MergeFrom(other.Vehicle);
      }
      if (other.fieldMask_ != null) {
        if (fieldMask_ == null) {
          FieldMask = new global::Google.Protobuf.WellKnownTypes.FieldMask();
        }
        FieldMask.MergeFrom(other.FieldMask);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (vehicle_ == null) {
              Vehicle = new global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle();
            }
            input.ReadMessage(Vehicle);
            break;
          }
          case 18: {
            if (fieldMask_ == null) {
              FieldMask = new global::Google.Protobuf.WellKnownTypes.FieldMask();
            }
            input.ReadMessage(FieldMask);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (vehicle_ == null) {
              Vehicle = new global::VBart.EventsDemo.Inventory.Aggregator.Domain.Aggregates.Vehicle();
            }
            input.ReadMessage(Vehicle);
            break;
          }
          case 18: {
            if (fieldMask_ == null) {
              FieldMask = new global::Google.Protobuf.WellKnownTypes.FieldMask();
            }
            input.ReadMessage(FieldMask);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
