// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: inventory.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VBart.EventsDemo.Grpc {

  /// <summary>Holder for reflection information generated from inventory.proto</summary>
  public static partial class InventoryReflection {

    #region Descriptor
    /// <summary>File descriptor for inventory.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InventoryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9pbnZlbnRvcnkucHJvdG8SH3ZiYXJ0LmV2ZW50c19kZW1vLmludmVudG9y",
            "eS5hcGkaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoTdmFsdWVfb2Jq",
            "ZWN0cy5wcm90bzLaBgoQSW52ZW50b3J5U2VydmljZRJxCglBZGRFbmdpbmUS",
            "MS52YmFydC5ldmVudHNfZGVtby5pbnZlbnRvcnkudmFsdWVfb2JqZWN0cy5F",
            "bmdpbmUaMS52YmFydC5ldmVudHNfZGVtby5pbnZlbnRvcnkudmFsdWVfb2Jq",
            "ZWN0cy5FbmdpbmUSdAoMVXBkYXRlRW5naW5lEjEudmJhcnQuZXZlbnRzX2Rl",
            "bW8uaW52ZW50b3J5LnZhbHVlX29iamVjdHMuRW5naW5lGjEudmJhcnQuZXZl",
            "bnRzX2RlbW8uaW52ZW50b3J5LnZhbHVlX29iamVjdHMuRW5naW5lElkKC0xp",
            "c3RFbmdpbmVzEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GjIudmJhcnQuZXZl",
            "bnRzX2RlbW8uaW52ZW50b3J5LnZhbHVlX29iamVjdHMuRW5naW5lcxJZCgxS",
            "ZW1vdmVFbmdpbmUSMS52YmFydC5ldmVudHNfZGVtby5pbnZlbnRvcnkudmFs",
            "dWVfb2JqZWN0cy5FbmdpbmUaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSdAoK",
            "QWRkVmVoaWNsZRIyLnZiYXJ0LmV2ZW50c19kZW1vLmludmVudG9yeS52YWx1",
            "ZV9vYmplY3RzLlZlaGljbGUaMi52YmFydC5ldmVudHNfZGVtby5pbnZlbnRv",
            "cnkudmFsdWVfb2JqZWN0cy5WZWhpY2xlEncKDVVwZGF0ZVZlaGljbGUSMi52",
            "YmFydC5ldmVudHNfZGVtby5pbnZlbnRvcnkudmFsdWVfb2JqZWN0cy5WZWhp",
            "Y2xlGjIudmJhcnQuZXZlbnRzX2RlbW8uaW52ZW50b3J5LnZhbHVlX29iamVj",
            "dHMuVmVoaWNsZRJbCgxMaXN0VmVoaWNsZXMSFi5nb29nbGUucHJvdG9idWYu",
            "RW1wdHkaMy52YmFydC5ldmVudHNfZGVtby5pbnZlbnRvcnkudmFsdWVfb2Jq",
            "ZWN0cy5WZWhpY2xlcxJbCg1SZW1vdmVWZWhpY2xlEjIudmJhcnQuZXZlbnRz",
            "X2RlbW8uaW52ZW50b3J5LnZhbHVlX29iamVjdHMuVmVoaWNsZRoWLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbXB0eUIYqgIVVkJhcnQuRXZlbnRzRGVtby5HcnBjYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::VBart.EventsDemo.Grpc.ValueObjects.ValueObjectsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
